name: Deploy app
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy app
        uses: isthatcentered/dist-to-ftp@master
        with:
          user: cv19ing20
          password: CuYSm5BHW735
          host: ftp://ftp.cv19ing20.altervista.org:21/
          port: 21
          path: Repository # Folder to deploy Ex: apps/frontend/dist or dist
          into: repo
