name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        # URL
        url: ftp://ftp.cv19ing20.altervista.org:21/Repository
        # FTP login name
        user: cv19ing20
        # FTP password
        password: CuYSm5BHW735
