name: Deploy app
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Simple FTP deploy
        uses: thebrainattic/simple-ftp-deploy-action@v2
        with:
          # FTP host
          ftp_host: ftp.cv19ing20.altervista.org
          # FTP username
          ftp_username: cv19ing20
          # FTP password
          ftp_password: CuYSm5BHW735
          # The local folder to copy
          local_source_dir: ./
          # The remote folder
          dist_target_dir: Repository
          # Delete files not present in the local folder on the remote folder
          
